import Head from 'next/head'
import Header from '@/components/header'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-col items-center justify-between min-h-screen p-24 bg-sky-50 dark:bg-slate-800 dark:text-gray-200">
        <div>
          <h1 className="text-6xl font-bold">Welcome to My Portfolio!</h1>
        </div>
      </main>
    </>
  )
}
